/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkArea.SignUp;




import Business.Business;
import Business.Person.Person;
import Business.Person.PersonDirectory;
import Business.ProfileWorkAreaMainFrame;
import Business.Profiles.Profile;
import Business.Profiles.StudentDirectory;
import Business.Profiles.StudentProfile;
import Business.UserAccounts.UserAccount;
import Business.UserAccounts.UserAccountDirectory;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.JOptionPane;

import javax.swing.JPanel;
import org.mindrot.jbcrypt.BCrypt;

/**
 *
 * @author revanth
 */
public class SignUpJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SignUpJPanel
     */
    JPanel CardSequencePanel;
    Business business;
    
    StudentDirectory studentDirectory = new StudentDirectory();
    UserAccountDirectory userAccountDirectory = new UserAccountDirectory();
    PersonDirectory personDirectory = new PersonDirectory();
    
    public SignUpJPanel(Business b, JPanel cs) {
        initComponents();
        
        
        this.business = b;
        this.CardSequencePanel = cs;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_title = new javax.swing.JLabel();
        lbl_SignUpCreatePassword = new javax.swing.JLabel();
        lbl_SignUpFirstName = new javax.swing.JLabel();
        txt_SignUpEmailID = new javax.swing.JTextField();
        jpf_SignUpCreatePassword = new javax.swing.JPasswordField();
        txt_SignUpSkillPulseID = new javax.swing.JTextField();
        lbl_SignUpLastName = new javax.swing.JLabel();
        txt_SignUpUserName = new javax.swing.JTextField();
        txt_SignUpFirstName = new javax.swing.JTextField();
        lbl_SignUpRole = new javax.swing.JLabel();
        lbl_SignUpConfirmPassword = new javax.swing.JLabel();
        jcb_SignUpRole = new javax.swing.JComboBox<>();
        txt_SignUpLastName = new javax.swing.JTextField();
        btn_SignUpSave = new javax.swing.JButton();
        jpf_SignUpConfirmPassword = new javax.swing.JPasswordField();
        lbl_SignUpEmailID = new javax.swing.JLabel();
        lbl_SignUpSkillPulseID = new javax.swing.JLabel();
        lbl_SignUpUserName = new javax.swing.JLabel();
        btn_Back = new javax.swing.JButton();

        lbl_title.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lbl_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_title.setText("Create a SkillPulse Account");

        lbl_SignUpCreatePassword.setText("Create Password: *");

        lbl_SignUpFirstName.setText("First Name: *");

        lbl_SignUpLastName.setText("Last Name: *");

        lbl_SignUpRole.setText("Role:");

        lbl_SignUpConfirmPassword.setText("Confirm Password: *");

        jcb_SignUpRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Student", "Professor" }));

        btn_SignUpSave.setText("Save");
        btn_SignUpSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SignUpSaveActionPerformed(evt);
            }
        });

        lbl_SignUpEmailID.setText("Email ID:");

        lbl_SignUpSkillPulseID.setText("SkillPulse ID: *");

        lbl_SignUpUserName.setText("User Name: *");

        btn_Back.setText("Back");
        btn_Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_title, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl_SignUpFirstName)
                            .addComponent(lbl_SignUpEmailID)
                            .addComponent(lbl_SignUpLastName)
                            .addComponent(lbl_SignUpSkillPulseID)
                            .addComponent(lbl_SignUpRole))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_SignUpFirstName)
                            .addComponent(txt_SignUpLastName)
                            .addComponent(txt_SignUpEmailID)
                            .addComponent(txt_SignUpSkillPulseID, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcb_SignUpRole, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl_SignUpUserName)
                            .addComponent(lbl_SignUpCreatePassword)
                            .addComponent(lbl_SignUpConfirmPassword))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_SignUpSave)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_Back))
                            .addComponent(txt_SignUpUserName)
                            .addComponent(jpf_SignUpCreatePassword)
                            .addComponent(jpf_SignUpConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(169, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(lbl_title)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_SignUpFirstName)
                    .addComponent(txt_SignUpFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_SignUpLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_SignUpLastName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_SignUpEmailID)
                    .addComponent(txt_SignUpEmailID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_SignUpSkillPulseID)
                    .addComponent(txt_SignUpSkillPulseID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_SignUpRole)
                    .addComponent(jcb_SignUpRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_SignUpUserName)
                    .addComponent(txt_SignUpUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_SignUpCreatePassword)
                    .addComponent(jpf_SignUpCreatePassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_SignUpConfirmPassword)
                    .addComponent(jpf_SignUpConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_SignUpSave)
                    .addComponent(btn_Back))
                .addContainerGap(49, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_SignUpSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SignUpSaveActionPerformed
        // TODO add your handling code here:
        SignUpValidations();

        //You need to go back to Login Page as well
    }//GEN-LAST:event_btn_SignUpSaveActionPerformed

    private void btn_BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BackActionPerformed
        //This is the code to go back to the previous Page

        CardSequencePanel.remove(this);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).previous(CardSequencePanel);
    }//GEN-LAST:event_btn_BackActionPerformed

    private void SignUpValidations(){
        
        if(txt_SignUpFirstName.getText().equals("") 
                || txt_SignUpLastName.getText().equals("")
                || txt_SignUpSkillPulseID.getText().equals("") 
                || jcb_SignUpRole.getSelectedItem().equals("None")
                || txt_SignUpUserName.getText().equals("") 
                || jpf_SignUpCreatePassword.getPassword().equals("")
                || jpf_SignUpConfirmPassword.getPassword().equals("")
                ){
            
            JOptionPane.showMessageDialog(this, "Madatory fields are missing");
        }
        else if(!Arrays.equals(jpf_SignUpCreatePassword.getPassword(), jpf_SignUpConfirmPassword.getPassword())){
            JOptionPane.showMessageDialog(this, "Password didn't Match!");
        }
        else if(personDirectory.findPerson(txt_SignUpSkillPulseID.getText()) != null){
            JOptionPane.showMessageDialog(this, "User already registered");
        }
        else {
            String FirstName = txt_SignUpFirstName.getText();
            String LastName = txt_SignUpLastName.getText();
            String EmailID = txt_SignUpEmailID.getText();
            String ID = txt_SignUpSkillPulseID.getText();
            String userName = txt_SignUpUserName.getText();
            String password = hashPassword(new String(jpf_SignUpCreatePassword.getPassword()));

            //Role
            if (jcb_SignUpRole.getSelectedItem().equals("Student")){
                
                if(userAccountDirectory.checkUserName(userName)){
                    JOptionPane.showMessageDialog(this, "UserName alread taken, please try using another");
                }
                else {
                    //System.out.println("Saveing Student profile");
                    Person p = personDirectory.newPerson(FirstName, LastName, EmailID, ID);
                    
                    StudentProfile studentProfile = studentDirectory.newStudentProfile(p);

                    System.out.println("Student List: ");
                    Output();

                    UserAccount user = userAccountDirectory.newUserAccount(studentProfile, userName, password);
                    
                    //CLEAR ALL THE FIELDS
                }
            }
            else{
                //Add Professor
            }
 
            
            
            
        }
        
        //Password
        
        
        
        
    }
    
    
    //For Netbeans Output
    public void Output(){
        ArrayList<StudentProfile> studentList = studentDirectory.getStudentlist();
        int i = 0;
        for(StudentProfile sp : studentList){
            Person p = sp.getPerson();
            System.out.println(i + ". [Firstname: " + p.getFirstName() + ", Lastname: " + p.getLastName()
            + ", EmailID: " + p.getEmailID() + ", Role: "+sp.getRole() + "]");
            
           i++;
        }
    }
    
    
    //Password Hashing
    public String hashPassword(String p){
        return BCrypt.hashpw(p, BCrypt.gensalt());
    }
    //Checking hashed Password
    public boolean checkPassword(String p, String encryptedPassword){
        System.out.println("HashedPassword is: " + BCrypt.checkpw(p, encryptedPassword));
        return BCrypt.checkpw(p, encryptedPassword);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Back;
    private javax.swing.JButton btn_SignUpSave;
    private javax.swing.JComboBox<String> jcb_SignUpRole;
    private javax.swing.JPasswordField jpf_SignUpConfirmPassword;
    private javax.swing.JPasswordField jpf_SignUpCreatePassword;
    private javax.swing.JLabel lbl_SignUpConfirmPassword;
    private javax.swing.JLabel lbl_SignUpCreatePassword;
    private javax.swing.JLabel lbl_SignUpEmailID;
    private javax.swing.JLabel lbl_SignUpFirstName;
    private javax.swing.JLabel lbl_SignUpLastName;
    private javax.swing.JLabel lbl_SignUpRole;
    private javax.swing.JLabel lbl_SignUpSkillPulseID;
    private javax.swing.JLabel lbl_SignUpUserName;
    private javax.swing.JLabel lbl_title;
    private javax.swing.JTextField txt_SignUpEmailID;
    private javax.swing.JTextField txt_SignUpFirstName;
    private javax.swing.JTextField txt_SignUpLastName;
    private javax.swing.JTextField txt_SignUpSkillPulseID;
    private javax.swing.JTextField txt_SignUpUserName;
    // End of variables declaration//GEN-END:variables
}
