/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkArea.SignUp;




import Business.Business;
import Business.Person.Person;
import Business.Person.PersonDirectory;
import Business.ProfileWorkAreaMainFrame;
import Business.Profiles.ProfessorDirectory;
import Business.Profiles.ProfessorProfile;
import Business.Profiles.Profile;
import Business.Profiles.StudentDirectory;
import Business.Profiles.StudentProfile;
import Business.UserAccounts.UserAccount;
import Business.UserAccounts.UserAccountDirectory;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.JOptionPane;

import javax.swing.JPanel;
import org.mindrot.jbcrypt.BCrypt;

/**
 *
 * @author revanth
 */
public class SignUpJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SignUpJPanel
     */
    JPanel CardSequencePanel;
    Business business;
    StudentDirectory studentDirectory = new StudentDirectory();
    ProfessorDirectory professorDirectory;
    
    
    
    
    public SignUpJPanel(Business b, JPanel cs) {
        this.business = b;
        this.CardSequencePanel = cs;
        professorDirectory = business.getProfessorDirectory();
        
        initComponents();
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_title = new javax.swing.JLabel();
        lbl_SignUpCreatePassword = new javax.swing.JLabel();
        lbl_SignUpFirstName = new javax.swing.JLabel();
        txt_SignUpEmailID = new javax.swing.JTextField();
        jpf_SignUpCreatePassword = new javax.swing.JPasswordField();
        txt_SignUpSkillPulseID = new javax.swing.JTextField();
        lbl_SignUpLastName = new javax.swing.JLabel();
        txt_SignUpUserName = new javax.swing.JTextField();
        txt_SignUpFirstName = new javax.swing.JTextField();
        lbl_SignUpRole = new javax.swing.JLabel();
        lbl_SignUpConfirmPassword = new javax.swing.JLabel();
        jcb_SignUpRole = new javax.swing.JComboBox<>();
        txt_SignUpLastName = new javax.swing.JTextField();
        btn_SignUpSave = new javax.swing.JButton();
        jpf_SignUpConfirmPassword = new javax.swing.JPasswordField();
        lbl_SignUpEmailID = new javax.swing.JLabel();
        lbl_SignUpSkillPulseID = new javax.swing.JLabel();
        lbl_SignUpUserName = new javax.swing.JLabel();
        btn_Back = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txt_SignUpSSN = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_SignUpPasswordNumber = new javax.swing.JTextField();

        lbl_title.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lbl_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_title.setText("Create a SkillPulse Account");

        lbl_SignUpCreatePassword.setText("Create Password: *");

        lbl_SignUpFirstName.setText("First Name: *");

        lbl_SignUpLastName.setText("Last Name: *");

        lbl_SignUpRole.setText("Role:");

        lbl_SignUpConfirmPassword.setText("Confirm Password: *");

        jcb_SignUpRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Student", "Professor" }));

        btn_SignUpSave.setText("Save");
        btn_SignUpSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SignUpSaveActionPerformed(evt);
            }
        });

        lbl_SignUpEmailID.setText("Email ID:");

        lbl_SignUpSkillPulseID.setText("SkillPulse ID: *");

        lbl_SignUpUserName.setText("User Name: *");

        btn_Back.setText("Back");
        btn_Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BackActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("SSN:");

        jLabel2.setText("Passport Number:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_title, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl_SignUpUserName)
                            .addComponent(lbl_SignUpCreatePassword)
                            .addComponent(lbl_SignUpConfirmPassword))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_SignUpSave)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_Back))
                            .addComponent(txt_SignUpUserName)
                            .addComponent(jpf_SignUpCreatePassword)
                            .addComponent(jpf_SignUpConfirmPassword, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(lbl_SignUpFirstName)
                            .addComponent(lbl_SignUpEmailID)
                            .addComponent(lbl_SignUpSkillPulseID)
                            .addComponent(lbl_SignUpRole)
                            .addComponent(lbl_SignUpLastName)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_SignUpFirstName)
                            .addComponent(txt_SignUpLastName)
                            .addComponent(txt_SignUpEmailID)
                            .addComponent(txt_SignUpSkillPulseID, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                            .addComponent(jcb_SignUpRole, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_SignUpSSN)
                            .addComponent(txt_SignUpPasswordNumber))))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(lbl_title)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_SignUpFirstName)
                    .addComponent(txt_SignUpFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_SignUpLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_SignUpLastName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_SignUpEmailID)
                    .addComponent(txt_SignUpEmailID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_SignUpSSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txt_SignUpPasswordNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_SignUpSkillPulseID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_SignUpSkillPulseID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jcb_SignUpRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_SignUpRole))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_SignUpUserName)
                    .addComponent(txt_SignUpUserName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_SignUpCreatePassword)
                    .addComponent(jpf_SignUpCreatePassword, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_SignUpConfirmPassword)
                    .addComponent(jpf_SignUpConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_SignUpSave)
                    .addComponent(btn_Back))
                .addGap(33, 33, 33))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_SignUpSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SignUpSaveActionPerformed
        // TODO add your handling code here:
        SignUpValidations();

        //You need to go back to Login Page as well
    }//GEN-LAST:event_btn_SignUpSaveActionPerformed

    private void btn_BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BackActionPerformed
        //This is the code to go back to the previous Page

        CardSequencePanel.remove(this);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).previous(CardSequencePanel);
    }//GEN-LAST:event_btn_BackActionPerformed

    private void SignUpValidations(){
        
        PersonDirectory personDirectory = business.getPersonDirectory();
        
        UserAccountDirectory userAccountDirectory = business.getUserAccountDirectory();
        
        String FirstName = txt_SignUpFirstName.getText();
        String LastName = txt_SignUpLastName.getText();
        String EmailID = txt_SignUpEmailID.getText();
        String ID = txt_SignUpSkillPulseID.getText();
        String userName = txt_SignUpUserName.getText();
        String ssn = txt_SignUpSSN.getText();
        String passportNumber = txt_SignUpPasswordNumber.getText();
        
        String createPassword = new String(jpf_SignUpCreatePassword.getPassword());
        String confirmPassword = new String(jpf_SignUpConfirmPassword.getPassword());
        
        System.out.println("Create Password: "+ createPassword);
        System.out.println("Confirm Password: "+ confirmPassword);
        
        if(txt_SignUpFirstName.getText().equals("") 
                || txt_SignUpLastName.getText().equals("")
                || txt_SignUpSkillPulseID.getText().equals("") 
                || jcb_SignUpRole.getSelectedItem().equals("None")
                || txt_SignUpUserName.getText().equals("") 
                || jpf_SignUpCreatePassword.getPassword().equals("")
                || jpf_SignUpConfirmPassword.getPassword().equals("")
                ){
            
            JOptionPane.showMessageDialog(this, "Madatory fields are missing");
        }
        
        /*
            *Password Constraint:
                * Password should contain at least 8 Characters
                * It should have Uppercase letter, lowercase letter, and special characters
        */
        //else if()
        else if(!userAccountDirectory.PasswordChecker(createPassword, confirmPassword)){
            JOptionPane.showMessageDialog(this, "Password didn't Match or It doesn't meet requirements");
        }
        else if(personDirectory.findPerson(txt_SignUpSkillPulseID.getText()) != null){
            JOptionPane.showMessageDialog(this, "User ID is already registered");
        }
        else if (userAccountDirectory.checkUserName(userName)) {
            JOptionPane.showMessageDialog(this, "UserName alread taken, please try using another");
        }
        else{   
//            String password = hashPassword(new String(jpf_SignUpCreatePassword.getPassword()));

            String password = BCrypt.hashpw(new String(jpf_SignUpCreatePassword.getPassword()), BCrypt.gensalt());

            //Role
            if (jcb_SignUpRole.getSelectedItem().equals("Student")) {
                //System.out.println("Saveing Student profile");
//              Person p = personDirectory.newPerson(FirstName, LastName, EmailID, ID);

//              PersonDirectory pad = business.getPersonDirectory();
                Person p = personDirectory.newPerson(FirstName, LastName, EmailID, ID);
                p.setSsn(ssn);
                p.setPassportNumber(passportNumber);

                StudentProfile studentProfile = studentDirectory.newStudentProfile(p);

                System.out.println("Student List: ");
                StudentOutput();

//              UserAccount user = userAccountDirectory.newUserAccount(studentProfile, userName, password);
//              UserAccountDirectory uad = business.getUserAccountDirectory();
                UserAccount user = userAccountDirectory.newUserAccount(studentProfile, userName, password, false);

                //CLEAR ALL THE FIELDS
                JOptionPane.showMessageDialog(this, "Information Saved successfully");

                txt_SignUpFirstName.setText("");
                txt_SignUpLastName.setText("");
                txt_SignUpEmailID.setText("");
                txt_SignUpSSN.setText("");
                txt_SignUpPasswordNumber.setText("");
                txt_SignUpSkillPulseID.setText("");
                jcb_SignUpRole.setSelectedItem("None");

                txt_SignUpUserName.setText("");
                jpf_SignUpCreatePassword.setText("");
                jpf_SignUpConfirmPassword.setText("");

            } 
            else {
                //Add Professor
                Person p = personDirectory.newPerson(FirstName, LastName, EmailID, ID);
                p.setSsn(ssn);
                p.setPassportNumber(passportNumber);
                
                ProfessorProfile professorProfile = professorDirectory.newProfessorProfile(p);
                
                System.out.println("Professor Profile: ");
                ProfessorOutput();
                
                UserAccount user = userAccountDirectory.newUserAccount(professorProfile, userName, password, false);
                
                //CLEAR ALL THE FIELDS
                JOptionPane.showMessageDialog(this, "Information Saved successfully");

                txt_SignUpFirstName.setText("");
                txt_SignUpLastName.setText("");
                txt_SignUpEmailID.setText("");
                txt_SignUpSSN.setText("");
                txt_SignUpPasswordNumber.setText("");
                txt_SignUpSkillPulseID.setText("");
                jcb_SignUpRole.setSelectedItem("None");

                txt_SignUpUserName.setText("");
                jpf_SignUpCreatePassword.setText("");
                jpf_SignUpConfirmPassword.setText("");

            }
            

        }
        System.out.println("");
        System.out.println("User Accounts: ");
        userAccountDirectory.UseraccountDirectoryOutput();
        
    }
    
    
    //For Netbeans StudentOutput
    public void StudentOutput(){
        ArrayList<StudentProfile> studentList = studentDirectory.getStudentlist();
        int i = 0;
        for(StudentProfile sp : studentList){
            Person p = sp.getPerson();
            System.out.println(i + ". [Firstname: " + p.getFirstName() + ", Lastname: " + p.getLastName()
            + ", EmailID: " + p.getEmailID() + ", Role: "+sp.getRole() + "]");
            
           i++;
        }
    }
    
    //For Netbeans ProfessorOutput
    public void ProfessorOutput(){
        ArrayList<ProfessorProfile> professorList = professorDirectory.getProfessorlist();
        int i = 0;
        for(ProfessorProfile pp : professorList){
            Person p = pp.getPerson();
            System.out.println(i + ". [Firstname: " + p.getFirstName() + ", Lastname: " + p.getLastName()
            + ", EmailID: " + p.getEmailID() + ", Role: "+pp.getRole() + "]");
            
            i++;
        }
    }
    
    
    //Password Hashing
    public String hashPassword(String p){
        return BCrypt.hashpw(p, BCrypt.gensalt());
    }
    //Checking hashed Password
    public boolean checkPassword(String p, String encryptedPassword){
        System.out.println("HashedPassword is: " + BCrypt.checkpw(p, encryptedPassword));
        return BCrypt.checkpw(p, encryptedPassword);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Back;
    private javax.swing.JButton btn_SignUpSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JComboBox<String> jcb_SignUpRole;
    private javax.swing.JPasswordField jpf_SignUpConfirmPassword;
    private javax.swing.JPasswordField jpf_SignUpCreatePassword;
    private javax.swing.JLabel lbl_SignUpConfirmPassword;
    private javax.swing.JLabel lbl_SignUpCreatePassword;
    private javax.swing.JLabel lbl_SignUpEmailID;
    private javax.swing.JLabel lbl_SignUpFirstName;
    private javax.swing.JLabel lbl_SignUpLastName;
    private javax.swing.JLabel lbl_SignUpRole;
    private javax.swing.JLabel lbl_SignUpSkillPulseID;
    private javax.swing.JLabel lbl_SignUpUserName;
    private javax.swing.JLabel lbl_title;
    private javax.swing.JTextField txt_SignUpEmailID;
    private javax.swing.JTextField txt_SignUpFirstName;
    private javax.swing.JTextField txt_SignUpLastName;
    private javax.swing.JTextField txt_SignUpPasswordNumber;
    private javax.swing.JTextField txt_SignUpSSN;
    private javax.swing.JTextField txt_SignUpSkillPulseID;
    private javax.swing.JTextField txt_SignUpUserName;
    // End of variables declaration//GEN-END:variables
}
