/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UserInterface;

import java.awt.CardLayout;
import java.awt.Component;

/**
 *
 * @author revanth
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        WorkAreaJPanel = new javax.swing.JPanel();
        LogInJPanel = new javax.swing.JPanel();
        lbl_UserName = new javax.swing.JLabel();
        lbl_Password = new javax.swing.JLabel();
        txt_UserName = new javax.swing.JTextField();
        jpf_Password = new javax.swing.JPasswordField();
        btn_LogIn = new javax.swing.JButton();
        btn_SignUp = new javax.swing.JButton();
        lbl_SubTitle = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 285, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        WorkAreaJPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "SkillPulse", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 1, 36), new java.awt.Color(0, 102, 255))); // NOI18N
        WorkAreaJPanel.setLayout(new java.awt.CardLayout());

        lbl_UserName.setText("User Name:");

        lbl_Password.setText("Password:");

        btn_LogIn.setText("Log In");

        btn_SignUp.setText("Sign Up");
        btn_SignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SignUpActionPerformed(evt);
            }
        });

        lbl_SubTitle.setText("Please enter your Login Details");

        javax.swing.GroupLayout LogInJPanelLayout = new javax.swing.GroupLayout(LogInJPanel);
        LogInJPanel.setLayout(LogInJPanelLayout);
        LogInJPanelLayout.setHorizontalGroup(
            LogInJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LogInJPanelLayout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addGroup(LogInJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_Password)
                    .addComponent(lbl_UserName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(LogInJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_SubTitle)
                    .addGroup(LogInJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(LogInJPanelLayout.createSequentialGroup()
                            .addComponent(btn_LogIn, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                            .addComponent(btn_SignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(txt_UserName, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jpf_Password, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(316, Short.MAX_VALUE))
        );
        LogInJPanelLayout.setVerticalGroup(
            LogInJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LogInJPanelLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(lbl_SubTitle)
                .addGap(33, 33, 33)
                .addGroup(LogInJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_UserName)
                    .addComponent(txt_UserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(LogInJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Password)
                    .addComponent(jpf_Password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(LogInJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_LogIn)
                    .addComponent(btn_SignUp))
                .addContainerGap(331, Short.MAX_VALUE))
        );

        WorkAreaJPanel.add(LogInJPanel, "card2");

        getContentPane().add(WorkAreaJPanel, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_SignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SignUpActionPerformed
        // TODO add your handling code here:
        
        SignUpJPanel SignUpPanel = new SignUpJPanel();
        WorkAreaJPanel.add("SignUpPanel", SignUpPanel);
        
        WorkAreaJPanel.remove(this);
        CardLayout layout = (CardLayout) WorkAreaJPanel.getLayout();
        layout.next(WorkAreaJPanel);
        
    }//GEN-LAST:event_btn_SignUpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel LogInJPanel;
    private javax.swing.JPanel WorkAreaJPanel;
    private javax.swing.JButton btn_LogIn;
    private javax.swing.JButton btn_SignUp;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jpf_Password;
    private javax.swing.JLabel lbl_Password;
    private javax.swing.JLabel lbl_SubTitle;
    private javax.swing.JLabel lbl_UserName;
    private javax.swing.JTextField txt_UserName;
    // End of variables declaration//GEN-END:variables
}
