/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface;

/**
 *
 * @author revanth
 */
public class SignUpJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SignUpJPanel
     */
    public SignUpJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_title = new javax.swing.JLabel();
        lbl_SignUpFirstName = new javax.swing.JLabel();
        jpf_SignUpCreatePassword = new javax.swing.JPasswordField();
        lbl_SignUpLastName = new javax.swing.JLabel();
        txt_SignUpFirstName = new javax.swing.JTextField();
        lbl_SignUpConfirmPassword = new javax.swing.JLabel();
        txt_SignUpLastName = new javax.swing.JTextField();
        jpf_SignUpConfirmPassword = new javax.swing.JPasswordField();
        lbl_SignUpEmailID = new javax.swing.JLabel();
        lbl_SignUpSkillPulseID = new javax.swing.JLabel();
        lbl_SignUpUserName = new javax.swing.JLabel();
        lbl_SignUpCreatePassword = new javax.swing.JLabel();
        txt_SignUpEmailID = new javax.swing.JTextField();
        txt_SignUpSkillPulseID = new javax.swing.JTextField();
        txt_SignUpUserName = new javax.swing.JTextField();
        lbl_SignUpRole = new javax.swing.JLabel();
        jcb_SignUpRole = new javax.swing.JComboBox<>();
        btn_SignUpSave = new javax.swing.JButton();

        lbl_title.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lbl_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_title.setText("Create a SkillPulse Account");

        lbl_SignUpFirstName.setText("First Name: *");

        lbl_SignUpLastName.setText("Last Name: *");

        lbl_SignUpConfirmPassword.setText("Confirm Password: *");

        lbl_SignUpEmailID.setText("Email ID:");

        lbl_SignUpSkillPulseID.setText("SkillPulse ID: *");

        lbl_SignUpUserName.setText("User Name: *");

        lbl_SignUpCreatePassword.setText("Create Password: *");

        lbl_SignUpRole.setText("Role: *");

        jcb_SignUpRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Student", "Professor" }));

        btn_SignUpSave.setText("Save and Log In");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_title, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl_SignUpFirstName)
                            .addComponent(lbl_SignUpEmailID)
                            .addComponent(lbl_SignUpLastName)
                            .addComponent(lbl_SignUpSkillPulseID)
                            .addComponent(lbl_SignUpRole))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_SignUpFirstName)
                            .addComponent(txt_SignUpLastName)
                            .addComponent(txt_SignUpEmailID)
                            .addComponent(txt_SignUpSkillPulseID, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcb_SignUpRole, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl_SignUpUserName)
                            .addComponent(lbl_SignUpCreatePassword)
                            .addComponent(lbl_SignUpConfirmPassword))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_SignUpSave)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txt_SignUpUserName)
                                .addComponent(jpf_SignUpCreatePassword)
                                .addComponent(jpf_SignUpConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(134, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(lbl_title)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_SignUpFirstName)
                    .addComponent(txt_SignUpFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_SignUpLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_SignUpLastName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_SignUpEmailID)
                    .addComponent(txt_SignUpEmailID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_SignUpSkillPulseID)
                    .addComponent(txt_SignUpSkillPulseID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_SignUpRole)
                    .addComponent(jcb_SignUpRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_SignUpUserName)
                    .addComponent(txt_SignUpUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_SignUpCreatePassword)
                    .addComponent(jpf_SignUpCreatePassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_SignUpConfirmPassword)
                    .addComponent(jpf_SignUpConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_SignUpSave)
                .addContainerGap(54, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_SignUpSave;
    private javax.swing.JComboBox<String> jcb_SignUpRole;
    private javax.swing.JPasswordField jpf_SignUpConfirmPassword;
    private javax.swing.JPasswordField jpf_SignUpCreatePassword;
    private javax.swing.JLabel lbl_SignUpConfirmPassword;
    private javax.swing.JLabel lbl_SignUpCreatePassword;
    private javax.swing.JLabel lbl_SignUpEmailID;
    private javax.swing.JLabel lbl_SignUpFirstName;
    private javax.swing.JLabel lbl_SignUpLastName;
    private javax.swing.JLabel lbl_SignUpRole;
    private javax.swing.JLabel lbl_SignUpSkillPulseID;
    private javax.swing.JLabel lbl_SignUpUserName;
    private javax.swing.JLabel lbl_title;
    private javax.swing.JTextField txt_SignUpEmailID;
    private javax.swing.JTextField txt_SignUpFirstName;
    private javax.swing.JTextField txt_SignUpLastName;
    private javax.swing.JTextField txt_SignUpSkillPulseID;
    private javax.swing.JTextField txt_SignUpUserName;
    // End of variables declaration//GEN-END:variables
}
