/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.WorkAreas.AdminRole.AdministerUserAccountsWorkResp;

import Business.Business;
import Business.Person.Person;
import Business.Person.PersonDirectory;
import Business.Profiles.Profile;
import Business.Profiles.StudentProfile;
import Business.UserAccounts.UserAccount;
import Business.UserAccounts.UserAccountDirectory;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Nikesh
 */
public class AdminUserAccount extends javax.swing.JPanel {

    /**
     * Creates new form ManageSuppliersJPanel
     */
    JPanel CardSequencePanel;

    UserAccount selecteduseraccount;
    Business business;
    UserAccountDirectory userAccountDirectory;
    PersonDirectory personDirectory;

    public AdminUserAccount(UserAccount sua, JPanel jp, Business b) {

        CardSequencePanel = jp;
        selecteduseraccount= sua;
        business = b;
        initComponents();
        //display user details here
        Profile profile = selecteduseraccount.getAssociatedPersonProfile();
        Person p = profile.getPerson();
        
        jCheckBox1.setSelected(selecteduseraccount.isIsEnabled());
        jTextField3.setText(selecteduseraccount.getRole());
        jTextField5.setText(selecteduseraccount.getUserLoginName());
        

    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Update = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Back1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 153, 153));
        setLayout(null);

        Update.setText("Update>>");
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });
        add(Update);
        Update.setBounds(500, 530, 100, 23);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel2.setText("Administer User Account");
        add(jLabel2);
        jLabel2.setBounds(21, 20, 550, 28);

        Back1.setText("<< Back");
        Back1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back1ActionPerformed(evt);
            }
        });
        add(Back1);
        Back1.setBounds(40, 530, 100, 23);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("isEnabled :");
        add(jLabel4);
        jLabel4.setBounds(150, 210, 70, 17);
        add(jCheckBox1);
        jCheckBox1.setBounds(270, 210, 19, 19);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Role :");
        add(jLabel5);
        jLabel5.setBounds(150, 270, 70, 17);

        jTextField3.setEditable(false);
        add(jTextField3);
        jTextField3.setBounds(270, 260, 190, 23);

        jLabel7.setText("Username :");
        add(jLabel7);
        jLabel7.setBounds(150, 100, 70, 17);
        add(jTextField5);
        jTextField5.setBounds(270, 100, 190, 23);

        jPasswordField1.setText("jPasswordField1");
        add(jPasswordField1);
        jPasswordField1.setBounds(270, 160, 190, 23);

        jLabel8.setText("Password :");
        add(jLabel8);
        jLabel8.setBounds(150, 160, 90, 17);
    }// </editor-fold>//GEN-END:initComponents

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
        // TODO add your handling code here:
        Profile profile = selecteduseraccount.getAssociatedPersonProfile();
        Person p = profile.getPerson();
        
        
        userAccountDirectory = business.getUserAccountDirectory();
        personDirectory = business.getPersonDirectory();
       
//        for(Person person : personDirectory.getPersonlist())
//        {
//            if(person.isMatch(p.getPersonId()))
//            {
//                person.setFirstName(jTextField1.getText());
//                person.setLastName(jTextField2.getText());
//                person.setEmailID(jTextField4.getText());
//                break;
//            }
//        }
        
        for(UserAccount ua : userAccountDirectory.getUserAccountList())
        {
            if (ua.isMatch(p.getPersonId())) {

                if (ua.getUserLoginName().equals(jTextField5.getText())) {
                    ua.setUsername(jTextField5.getText());
                    ua.setIsEnabled(jCheckBox1.isSelected());
                    ManageUserAccountsJPanel manageUsers = new ManageUserAccountsJPanel(business, CardSequencePanel);
                    
                    Component component = CardSequencePanel.getComponent(1);
                    ManageUserAccountsJPanel manageusers = (ManageUserAccountsJPanel) component;
                    
                    CardSequencePanel.remove(this);
                    ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
                    manageusers.refreshTable();
                    
                } else if (!ua.getUserLoginName().equals(jTextField5.getText())) {
                    if (userAccountDirectory.checkUserName(jTextField5.getText())) {
                        JOptionPane.showMessageDialog(this, "UserName alread taken, please try using another");
                        jTextField5.setText(ua.getUserLoginName());
                        
                    } else {
                        ua.setUsername(jTextField5.getText());
                        ua.setIsEnabled(jCheckBox1.isSelected());
                        Component component = CardSequencePanel.getComponent(1);
                        ManageUserAccountsJPanel manageusers = (ManageUserAccountsJPanel) component;

                        CardSequencePanel.remove(this);
                        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
                        manageusers.refreshTable();
                    }
                }
            }
        }


    }//GEN-LAST:event_UpdateActionPerformed

    private void Back1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back1ActionPerformed
        // TODO add your handling code here:
         CardSequencePanel.remove(this);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).previous(CardSequencePanel);

//        CardSequencePanel.remove(this);
//        ((java.awt.CardLayout) CardSequencePanel.getLayout()).previous(CardSequencePanel);


    }//GEN-LAST:event_Back1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back1;
    private javax.swing.JButton Update;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables

}
